export default [
  {
    id: 0,
    img: "/product__1.jpg",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 1,
    img: "/product__2.jpg",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 2,
    img: "/product__3.jpg",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 3,
    img: "/product__4.jpg",
    name: "Wild Silk Finish Lipstick",
    price: 41.0,
    category: ["lipsticks", "makeup"],
    sale: true,
  },
  {
    id: 4,
    img: "/product__5.jpg",
    name: "Goat Milk Lotion For Body",
    price: 15.0,
    category: ["skin care"],
    sale: false,
  },
  {
    id: 5,
    img: "/product__6.jpg",
    name: "Lead Gel Nail Polish",
    price: 18.0,
    category: ["nail & wax"],
    sale: false,
  },
  {
    id: 6,
    img: "/product__7.jpg",
    name: "Lead Gel Nail Polish",
    price: 18.0,
    category: ["nail & wax"],
    sale: true,
  },
  {
    id: 7,
    img: "/product__8.jpg",
    name: "Lead Gel Nail Polish",
    price: 18.0,
    category: ["nail & wax"],
  },
  {
    id: 8,
    img: "/product__9.jpg",
    name: "Lead Gel Nail Polish",
    price: 18.0,
    category: ["nail & wax"],
    sale: false,
  },
  {
    id: 9,
    img: "/product__11.jpg",
    name: "Washable Bold Eye Mascara",
    price: 55.0,
    category: ["makeup"],
    sale: true,
  },
  {
    id: 10,
    img: "/product__12.jpg",
    name: "Washable Bold Eye Mascara",
    price: 55.0,
    category: ["makeup"],
    sale: false,
  },
  {
    id: 11,
    img: "/product__13.jpg",
    name: "Cleanser with Salicylic Acid",
    price: 16.0,
    category: ["skin care"],
    sale: false,
  },
  {
    id: 12,
    img: "/product__14.jpg",
    name: "Xtreme Wear Nail Polish",
    price: 55.0,
    category: ["makeup", "nail & wax"],
    sale: true,
  },
  {
    id: 13,
    img: "/product__15.jpg",
    name: "Xtreme Wear Nail Polish",
    price: 55.0,
    category: ["makeup", "nail & wax"],
    sale: false,
  },
  {
    id: 14,
    img: "/product__16.jpg",
    name: "Xtreme Wear Nail Polish",
    price: 55.0,
    category: ["makeup", "nail & wax"],
    sale: false,
  },
  {
    id: 15,
    img: "/product__17.jpg",
    name: "Xtreme Wear Nail Polish",
    price: 55.0,
    category: ["makeup", "nail & wax"],
    sale: true,
  },
  {
    id: 16,
    img: "/product__18.jpg",
    name: "Glam Liquid Eyeshadow",
    price: 16.0,
    category: ["makeup"],
    sale: false,
  },
  {
    id: 17,
    img: "/product__19.jpg",
    name: "Glam Liquid Eyeshadow",
    price: 16.0,
    category: ["makeup"],
    sale: true,
  },
  {
    id: 18,
    img: "/product__20.jpg",
    name: "Glam Liquid Eyeshadow",
    price: 16.0,
    category: ["makeup"],
    sale: false,
  },
  {
    id: 19,
    img: "/product__21.jpg",
    name: "Glam Liquid Eyeshadow",
    price: 16.0,
    category: ["makeup"],
    sale: false,
  },
  {
    id: 20,
    img: "/product__22.jpg",
    name: "NYX Matte Lipstick",
    price: 25.0,
    category: ["makeup", "lipsticks"],
    sale: true,
  },
  {
    id: 21,
    img: "/product__23.jpg",
    name: "Baby Oil",
    price: 20.0,
    category: ["skin care"],
    sale: false,
  },
  {
    id: 22,
    img: "/product__24.jpg",
    name: "Hansen Vitamin C cleanser",
    price: 15.0,
    category: ["skin care"],
    sale: false,
  },
  {
    id: 23,
    img: "/product__25.jpg",
    name: "Arabica Coffee Scrub Skin",
    price: 18.0,
    category: ["skin care"],
    sale: true,
  },
  {
    id: 24,
    img: "/product__26.jpg",
    name: "Rose Massage Oil",
    price: 25.0,
    category: ["skin care"],
    sale: false,
  },
  {
    id: 25,
    img: "/product__27.jpg",
    name: "Secret Tease Candy Noir",
    price: 12.0,
    category: ["makeup"],
    sale: false,
  },
  {
    id: 26,
    img: "/product__28.jpg",
    name: "Gloss Pink With Collagen",
    price: 29.0,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 27,
    img: "/product__29.jpg",
    name: "Gloss Pink With Collagen",
    price: 29.0,
    category: ["lipsticks"],
    sale: true,
  },
  {
    id: 28,
    img: "/product__30.jpg",
    name: "Minerals Matte Lipstick",
    price: 43.0,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 29,
    img: "/product__31.jpg",
    name: "Minerals Matte Lipstick",
    price: 43.0,
    category: ["lipsticks"],
    sale: true,
  },
  {
    id: 30,
    img: "/product__32.jpg",
    name: "Minerals Matte Lipstick",
    price: 43.0,
    category: ["lipsticks"],
    sale: false,
  },
  {
    id: 31,
    img: "/product__33.jpg",
    name: "Natural Tea Body Wash",
    price: 38.0,
    category: ["skin care"],
    sale: false,
  },
  {
    id: 32,
    img: "/product__34.jpg",
    name: "Touch Keratosis Pilaris",
    price: 29.0,
    category: ["skin care"],
    sale: false,
  },
  {
    id: 33,
    img: "/product__35.jpg",
    name: "Yves Saint Laurent Libre",
    price: 23.0,
    category: ["makeup"],
    sale: false,
  },
];
